INSERT INTO EMPLOYEE (id, name) VALUES (1, 'DHONI');
INSERT INTO EMPLOYEE (id, name) VALUES (2, 'KHOLI');

INSERT INTO DEPARTMENT (id , name) VALUES (1 , 'MECH');
INSERT INTO DEPARTMENT (id , name) VALUES (2 , 'CS');